// apps/react-bootstrap-demo/src/app/app.tsx
import { lazy, Suspense, type ComponentType } from 'react';
import { Route, Routes } from 'react-router-dom';
import { AppShell } from './shell/AppShell';
import { HomePage } from './pages/HomePage';
import { ComingSoonPage } from './pages/ComingSoonPage';

/**
 * React.lazy() expects a module with a `default` export. Our pages use
 * named exports for grep-friendliness, so we adapt with this tiny helper
 * that picks the named export and wraps it as the lazy module's default.
 */
function lazyNamed<P>(
  loader: () => Promise<Record<string, ComponentType<P>>>,
  name: string,
): ComponentType<P> {
  return lazy(() => loader().then((m) => ({ default: m[name] })));
}

// Per-component pages are added incrementally in the WC-extraction PRs
// (PR-4 through PR-9). Until then every non-home route renders the
// ComingSoonPage placeholder so the AppShell's sidebar links don't 404.
//
// Pages are code-split via lazyNamed so each page becomes its own JS
// chunk — the initial bundle only ships the shell + router + Home.
const CalendarPage     = lazyNamed(() => import('./pages/CalendarPage'),     'CalendarPage');
const CardPage         = lazyNamed(() => import('./pages/CardPage'),         'CardPage');
const CheckboxPage     = lazyNamed(() => import('./pages/CheckboxPage'),     'CheckboxPage');
const DatatablePage    = lazyNamed(() => import('./pages/DatatablePage'),    'DatatablePage');
const DatepickerPage   = lazyNamed(() => import('./pages/forms/DatepickerPage'),     'DatepickerPage');
const DatetimePickerPage = lazyNamed(() => import('./pages/forms/DatetimePickerPage'), 'DatetimePickerPage');
const SelectPage       = lazyNamed(() => import('./pages/forms/SelectPage'),         'SelectPage');
const CodeSnippetPage  = lazyNamed(() => import('./pages/CodeSnippetPage'),  'CodeSnippetPage');
const PaginationPage   = lazyNamed(() => import('./pages/PaginationPage'),   'PaginationPage');
const RadioPage        = lazyNamed(() => import('./pages/RadioPage'),        'RadioPage');
const TimepickerPage   = lazyNamed(() => import('./pages/forms/TimepickerPage'),     'TimepickerPage');
const MultiRangePage   = lazyNamed(() => import('./pages/forms/MultiRangePage'),     'MultiRangePage');
const OtpInputPage     = lazyNamed(() => import('./pages/advanced/OtpInputPage'),    'OtpInputPage');
const DockPage         = lazyNamed(() => import('./pages/enterprise/DockPage'),        'DockPage');
const TileManagerPage  = lazyNamed(() => import('./pages/enterprise/TileManagerPage'), 'TileManagerPage');
const FileManagerPage  = lazyNamed(() => import('./pages/enterprise/FileManagerPage'), 'FileManagerPage');
const QueryBuilderPage = lazyNamed(() => import('./pages/enterprise/QueryBuilderPage'), 'QueryBuilderPage');
const RibbonPage       = lazyNamed(() => import('./pages/enterprise/RibbonPage'),       'RibbonPage');
const ToggleButtonPage = lazyNamed(() => import('./pages/ToggleButtonPage'), 'ToggleButtonPage');
const TabControlPage   = lazyNamed(() => import('./pages/TabControlPage'),   'TabControlPage');
const TreeviewPage     = lazyNamed(() => import('./pages/TreeviewPage'),     'TreeviewPage');
const TreeSelectPage   = lazyNamed(() => import('./pages/TreeSelectPage'),   'TreeSelectPage');
const SplitterPage     = lazyNamed(() => import('./pages/advanced/SplitterPage'), 'SplitterPage');
const SchedulerPage    = lazyNamed(() => import('./pages/enterprise/SchedulerPage'), 'SchedulerPage');
const TimelinePage     = lazyNamed(() => import('./pages/enterprise/TimelinePage'),  'TimelinePage');
const ShellPage        = lazyNamed(() => import('./pages/enterprise/ShellPage'),     'ShellPage');

function PageFallback() {
  return (
    <div className="demo-page text-body-secondary">
      <div className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true" />
      Loading…
    </div>
  );
}

export function App() {
  return (
    <AppShell>
      <Suspense fallback={<PageFallback />}>
        <Routes>
          <Route path="/" element={<HomePage />} />
          {/* Basic */}
          <Route path="/basic/calendar" element={<CalendarPage />} />
          <Route path="/basic/card" element={<CardPage />} />
          <Route path="/basic/checkbox" element={<CheckboxPage />} />
          <Route path="/basic/code-snippet" element={<CodeSnippetPage />} />
          <Route path="/basic/forms/datepicker" element={<DatepickerPage />} />
          <Route path="/basic/forms/datetime-picker" element={<DatetimePickerPage />} />
          <Route path="/basic/forms/select" element={<SelectPage />} />
          <Route path="/basic/forms/timepicker" element={<TimepickerPage />} />
          <Route path="/basic/forms/multi-range" element={<MultiRangePage />} />
          <Route path="/basic/pagination" element={<PaginationPage />} />
          <Route path="/basic/radio" element={<RadioPage />} />
          <Route path="/basic/toggle-button" element={<ToggleButtonPage />} />
          <Route path="/basic/tab-control" element={<TabControlPage />} />
          <Route path="/basic/treeview" element={<TreeviewPage />} />
          <Route path="/basic/tree-select" element={<TreeSelectPage />} />
          {/* Advanced */}
          <Route path="/advanced/otp-input" element={<OtpInputPage />} />
          <Route path="/advanced/splitter" element={<SplitterPage />} />
          {/* Enterprise */}
          <Route path="/enterprise/dock" element={<DockPage />} />
          <Route path="/enterprise/tile-manager" element={<TileManagerPage />} />
          <Route path="/enterprise/datatables" element={<DatatablePage />} />
          <Route path="/enterprise/file-manager" element={<FileManagerPage />} />
          <Route path="/enterprise/query-builder" element={<QueryBuilderPage />} />
          <Route path="/enterprise/ribbon" element={<RibbonPage />} />
          <Route path="/enterprise/scheduler" element={<SchedulerPage />} />
          <Route path="/enterprise/timeline" element={<TimelinePage />} />
          <Route path="/enterprise/shell" element={<ShellPage />} />
          <Route path="*" element={<ComingSoonPage />} />
        </Routes>
      </Suspense>
    </AppShell>
  );
}

export default App;

// apps/vue-bootstrap-demo/src/app/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
import { BsShell } from '@mintplayer/vue-bootstrap/shell';
import FrameworkLinks from './FrameworkLinks.vue';
import pkg from '@mintplayer/vue-bootstrap/package.json';

// Read the version from the wrapper package so the navbar tracks
// @mintplayer/vue-bootstrap rather than a hardcoded string, mirroring the
// Angular demo's GitHub link.
const version = pkg.version;
const repoUrl = 'https://github.com/MintPlayer/mintplayer-ng-bootstrap';

const SECTIONS = [
  {
    title: 'Basic',
    routes: [
      { path: '/basic/card', label: 'Card' },
      { path: '/basic/calendar', label: 'Calendar' },
      { path: '/basic/forms/datepicker', label: 'Datepicker' },
      { path: '/basic/forms/datetime-picker', label: 'Datetime picker' },
      { path: '/basic/forms/timepicker', label: 'Timepicker' },
      { path: '/basic/forms/multi-range', label: 'Multi-range' },
      { path: '/basic/forms/select', label: 'Select' },
      { path: '/basic/checkbox', label: 'Checkbox' },
      { path: '/basic/radio', label: 'Radio' },
      { path: '/basic/toggle-button', label: 'Toggle button' },
      { path: '/basic/pagination', label: 'Pagination' },
      { path: '/basic/treeview', label: 'Treeview' },
      { path: '/basic/tree-select', label: 'Tree select' },
      { path: '/basic/tab-control', label: 'Tab control' },
      { path: '/basic/code-snippet', label: 'Code snippet' },
    ],
  },
  {
    title: 'Advanced',
    routes: [
      { path: '/advanced/splitter', label: 'Splitter' },
      { path: '/advanced/otp-input', label: 'OTP input' },
    ],
  },
  {
    title: 'Enterprise',
    routes: [
      { path: '/enterprise/scheduler', label: 'Scheduler' },
      { path: '/enterprise/timeline', label: 'Timeline' },
      { path: '/enterprise/dock', label: 'Dock manager' },
      { path: '/enterprise/ribbon', label: 'Ribbon' },
      { path: '/enterprise/tile-manager', label: 'Tile manager' },
      { path: '/enterprise/query-builder', label: 'Query builder' },
      { path: '/enterprise/datatables', label: 'Datatable' },
      { path: '/enterprise/file-manager', label: 'File manager' },
      { path: '/enterprise/shell', label: 'Shell' },
    ],
  },
];
</script>

<template>
  <BsShell breakpoint="md" size="14rem" class="app-shell">
    <!-- Top bar: the shell renders the hamburger toggle at its left; this slot
         fills the rest with the brand + framework links. -->
    <div slot="topbar" class="d-flex align-items-center px-3 py-2 app-shell-header flex-grow-1">
      <RouterLink to="/" class="text-decoration-none fw-semibold text-body fs-5">
        @mintplayer/vue-bootstrap
      </RouterLink>
      <span class="text-body-secondary small">demo</span>
      <div class="flex-grow-1" />
      <FrameworkLinks />
      <a
        class="github-link"
        :href="repoUrl"
        target="_blank"
        rel="noreferrer"
        title="@mintplayer/vue-bootstrap on GitHub"
      >
        <span class="github-link-version">{{ version }}</span>
        <svg class="github-link-icon" viewBox="0 0 16 16" aria-hidden="true">
          <path
            fill="currentColor"
            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8Z"
          />
        </svg>
      </a>
    </div>
    <nav slot="sidebar" class="border-end bg-body-tertiary p-3 app-shell-sidebar">
        <div v-for="section in SECTIONS" :key="section.title" class="mb-3">
          <div class="text-uppercase small text-body-secondary fw-semibold mb-2">{{ section.title }}</div>
          <ul class="list-unstyled mb-0">
            <li v-for="r in section.routes" :key="r.path">
              <RouterLink
                :to="r.path"
                class="d-block px-2 py-1 rounded text-decoration-none text-body"
                active-class="bg-primary-subtle text-primary fw-semibold"
              >
                {{ r.label }}
              </RouterLink>
            </li>
          </ul>
        </div>
      </nav>
      <main class="app-shell-main flex-grow-1">
        <RouterView />
      </main>
    </BsShell>
</template>
