// libs/mintplayer-vue-bootstrap/ribbon/src/BsQuickAccessToolbar.vue
<script setup lang="ts">
// Side-effect-registers <mp-quick-access-toolbar> via the upstream WC entry.
import '@mintplayer/web-components/ribbon';

defineOptions({ inheritAttrs: false });
</script>

<template>
  <mp-quick-access-toolbar v-bind="$attrs">
    <slot />
  </mp-quick-access-toolbar>
</template>

// libs/mintplayer-react-bootstrap/ribbon/src/BsQuickAccessToolbar.tsx
import * as React from 'react';
import { createComponent } from '@lit/react';
import { MpQuickAccessToolbar } from '@mintplayer/web-components/ribbon';
/**
 * React wrapper for `<mp-quick-access-toolbar>`. Side-effect-registers the WC via
 * the import above. Typed props/events extend off MpQuickAccessToolbar;
 * hand-edit this file to add an `events: { onXxx: 'xxx' as EventName<...> }`
 * block if you need typed event listeners.
 */
export const BsQuickAccessToolbar = createComponent({
  react: React,
  tagName: 'mp-quick-access-toolbar',
  elementClass: MpQuickAccessToolbar,
});
