// libs/mintplayer-vue-bootstrap/ribbon/src/BsRibbonContextualTabSet.vue
<script setup lang="ts">
// Side-effect-registers <mp-ribbon-contextual-tab-set> via the upstream WC entry.
import '@mintplayer/web-components/ribbon';

defineOptions({ inheritAttrs: false });
</script>

<template>
  <mp-ribbon-contextual-tab-set v-bind="$attrs">
    <slot />
  </mp-ribbon-contextual-tab-set>
</template>

// libs/mintplayer-react-bootstrap/ribbon/src/BsRibbonContextualTabSet.tsx
import * as React from 'react';
import { createComponent } from '@lit/react';
import { MpRibbonContextualTabSet } from '@mintplayer/web-components/ribbon';
/**
 * React wrapper for `<mp-ribbon-contextual-tab-set>`. Side-effect-registers the WC via
 * the import above. Typed props/events extend off MpRibbonContextualTabSet;
 * hand-edit this file to add an `events: { onXxx: 'xxx' as EventName<...> }`
 * block if you need typed event listeners.
 */
export const BsRibbonContextualTabSet = createComponent({
  react: React,
  tagName: 'mp-ribbon-contextual-tab-set',
  elementClass: MpRibbonContextualTabSet,
});
