// libs/mintplayer-react-bootstrap/signature-pad/src/BsSignaturePad.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { MpSignaturePadElement, type Signature } from '@mintplayer/web-components/signature-pad';

/**
 * React wrapper for `<mp-signature-pad>`. Side-effect-registers the WC via
 * the import above. The `signature` model object is assigned as a property
 * by `@lit/react`; `signature-change` fires on every mutation (stroke point,
 * typed character, undo, clear).
 */
export const BsSignaturePad = createComponent({
  react: React,
  tagName: 'mp-signature-pad',
  elementClass: MpSignaturePadElement,
  events: {
    onSignatureChange: 'signature-change' as EventName<CustomEvent<Signature>>,
  },
});

// libs/mintplayer-vue-bootstrap/signature-pad/src/BsSignaturePad.vue
<script setup lang="ts">
// Side-effect-registers <mp-signature-pad> via the upstream WC entry.
import '@mintplayer/web-components/signature-pad';
import type { MpSignaturePadElement, Signature } from '@mintplayer/web-components/signature-pad';
import { ref, watch, onMounted } from 'vue';

defineOptions({ inheritAttrs: false });

// v-model surface: `signature: Signature` + the WC's `signature-change` event.
const modelValue = defineModel<Signature>();
const el = ref<MpSignaturePadElement | null>(null);

const syncToEl = (v: Signature | undefined) => {
  if (el.value) el.value.signature = v ?? { strokes: [] };
};

onMounted(() => syncToEl(modelValue.value));
watch(modelValue, syncToEl);

function onSignatureChange(e: Event) {
  modelValue.value = (e as CustomEvent<Signature>).detail;
}
</script>

<template>
  <mp-signature-pad
    ref="el"
    v-bind="$attrs"
    @signature-change="onSignatureChange"
  />
</template>
