// libs/mintplayer-react-bootstrap/toggle-button/src/BsToggleButton.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { MpToggleButton, type ToggleChangeEventDetail } from '@mintplayer/web-components/toggle-button';
/**
 * React wrapper for `<mp-toggle-button>`. Side-effect-registers the WC via
 * the import above. The WC fires a native-style `change` CustomEvent with
 * `{ checked, value }` detail; surface it as a typed `onChange` React prop.
 */
export const BsToggleButton = createComponent({
  react: React,
  tagName: 'mp-toggle-button',
  elementClass: MpToggleButton,
  events: {
    onChange: 'change' as EventName<CustomEvent<ToggleChangeEventDetail>>,
  },
});

// libs/mintplayer-vue-bootstrap/toggle-button/src/BsToggleButton.vue
<script setup lang="ts">
// Side-effect-registers <mp-toggle-button> via the upstream WC entry.
import '@mintplayer/web-components/toggle-button';
import type { MpToggleButton, ToggleChangeEventDetail } from '@mintplayer/web-components/toggle-button';
import { ref, watch, onMounted } from 'vue';
defineOptions({ inheritAttrs: false });

// The toggle-button WC's v-model surface is the `checked` property
// (boolean) + the `change` CustomEvent<{ checked, value }>.
const modelValue = defineModel<boolean>();
const el = ref<MpToggleButton | null>(null);

const syncToEl = (v: boolean | undefined) => {
  if (el.value) el.value.checked = !!v;
};

onMounted(() => syncToEl(modelValue.value));
watch(modelValue, syncToEl);

function onChange(e: Event) {
  const detail = (e as CustomEvent<ToggleChangeEventDetail>).detail;
  modelValue.value = detail.checked;
}
</script>

<template>
  <mp-toggle-button
    ref="el"
    v-bind="$attrs"
    @change="onChange"
  >
    <slot />
  </mp-toggle-button>
</template>
