// libs/mintplayer-vue-bootstrap/timeline/src/BsTimeline.vue
<script setup lang="ts">
import '@mintplayer/web-components/timeline';
import { resolveSides, type MpTimeline } from '@mintplayer/web-components/timeline';
import type {
  TimelineAlign,
  TimelineItem,
  TimelineItemClickDetail,
  TimelineItemContext,
  TimelineOrientation,
  TimelineSelectable,
  TimelineSelectionChangeDetail,
} from '@mintplayer/web-components/timeline-core';
import { computed, onBeforeUnmount, onMounted, ref, useSlots, watch } from 'vue';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    items?: TimelineItem[];
    orientation?: TimelineOrientation;
    align?: TimelineAlign;
    reverse?: boolean;
    selectable?: TimelineSelectable;
    /** v-model:selection — array of selected items (identity via id). */
    selection?: TimelineItem[];
  }>(),
  { orientation: 'vertical', align: 'start', reverse: false, selectable: 'none' },
);

const emit = defineEmits<{
  (e: 'item-click', detail: TimelineItemClickDetail): void;
  (e: 'update:selection', selected: TimelineItem[]): void;
}>();

const slots = useSlots();
const hasSlots = computed(
  () => !!(slots.marker || slots.title || slots.timestamp || slots.opposite || slots.content),
);
const lowering = computed(() => hasSlots.value && !!props.items?.length);

const el = ref<MpTimeline | null>(null);

const idOf = (item: TimelineItem, i: number): string | number => item.id ?? i;
const sides = computed(() => resolveSides(props.items?.length ?? 0, props.align, props.reverse));
const ctxFor = (item: TimelineItem, i: number): TimelineItemContext => {
  const len = props.items?.length ?? 0;
  const visualIndex = props.reverse ? len - 1 - i : i;
  return {
    index: i,
    visualIndex,
    isFirst: visualIndex === 0,
    isLast: visualIndex === len - 1,
    orientation: props.orientation,
    side: sides.value[i] ?? 'start',
  };
};
const timeAttr = (item: TimelineItem): string | undefined =>
  item.time instanceof Date ? item.time.toLocaleDateString() : item.time;

const onClick = (e: Event): void => emit('item-click', (e as CustomEvent<TimelineItemClickDetail>).detail);
const onSel = (e: Event): void => {
  const detail = (e as CustomEvent<TimelineSelectionChangeDetail>).detail;
  const its = props.items;
  if (its && its.length) {
    const ids = el.value?.selectedIds ?? detail.selected.map((m, i) => m.id ?? i);
    const byId = new Map(its.map((it, i) => [idOf(it, i), it] as const));
    emit(
      'update:selection',
      ids.map((id) => byId.get(id)).filter((x): x is TimelineItem => x !== undefined),
    );
  } else {
    emit('update:selection', detail.selected);
  }
};

const syncItems = (): void => {
  if (!el.value) return;
  el.value.items = !lowering.value && props.items ? props.items : [];
};
const syncSelection = (): void => {
  if (!el.value || props.selectable === 'none') return;
  el.value.selectedIds = (props.selection ?? []).map((it, i) => idOf(it, i));
};

onMounted(() => {
  el.value?.addEventListener('item-click', onClick);
  el.value?.addEventListener('selection-change', onSel);
  syncItems();
  syncSelection();
});
onBeforeUnmount(() => {
  el.value?.removeEventListener('item-click', onClick);
  el.value?.removeEventListener('selection-change', onSel);
});
watch(() => props.items, syncItems);
watch(lowering, syncItems);
watch(() => props.selection, syncSelection);
watch(() => props.selectable, syncSelection);
</script>

<template>
  <mp-timeline
    ref="el"
    :orientation="orientation"
    :align="align"
    :reverse="reverse ? '' : undefined"
    :selectable="selectable"
    v-bind="$attrs"
  >
    <template v-if="lowering">
      <mp-timeline-item
        v-for="(item, i) in items ?? []"
        :key="item.id ?? i"
        :item-id="item.id ?? undefined"
        :title="item.title ?? undefined"
        :description="item.description ?? undefined"
        :time="timeAttr(item) ?? undefined"
        :icon="item.icon ?? undefined"
        :color="item.color ?? undefined"
        :item-class="item.cssClass ?? undefined"
        :disabled="item.disabled ? '' : undefined"
      >
        <span v-if="slots.marker" slot="marker"><slot name="marker" :item="item" :ctx="ctxFor(item, i)" /></span>
        <span v-if="slots.title" slot="title"><slot name="title" :item="item" :ctx="ctxFor(item, i)" /></span>
        <span v-if="slots.timestamp" slot="opposite"><slot name="timestamp" :item="item" :ctx="ctxFor(item, i)" /></span>
        <span v-if="slots.opposite" slot="opposite"><slot name="opposite" :item="item" :ctx="ctxFor(item, i)" /></span>
        <div v-if="slots.content" slot="content"><slot name="content" :item="item" :ctx="ctxFor(item, i)" /></div>
      </mp-timeline-item>
    </template>
    <slot v-else />
  </mp-timeline>
</template>

// libs/mintplayer-react-bootstrap/timeline/src/BsTimeline.tsx
import * as React from 'react';
// Side-effect import: registers <mp-timeline> + <mp-timeline-item>.
import '@mintplayer/web-components/timeline';
import { resolveSides, type MpTimeline } from '@mintplayer/web-components/timeline';
import type {
  TimelineAlign,
  TimelineItem,
  TimelineItemClickDetail,
  TimelineItemContext,
  TimelineOrientation,
  TimelineSelectable,
  TimelineSelectionChangeDetail,
} from '@mintplayer/web-components/timeline-core';

type RenderProp = (item: TimelineItem, ctx: TimelineItemContext) => React.ReactNode;

export interface BsTimelineProps {
  items?: TimelineItem[];
  orientation?: TimelineOrientation;
  align?: TimelineAlign;
  reverse?: boolean;
  selectable?: TimelineSelectable;
  /** Controlled selection (array of items, identity via `id`). */
  selection?: TimelineItem[];
  onSelectionChange?: (selected: TimelineItem[]) => void;
  onItemClick?: (detail: TimelineItemClickDetail) => void;
  /** Render-props — lowered into `<mp-timeline-item>` children. */
  renderMarker?: RenderProp;
  renderTitle?: RenderProp;
  renderTimestamp?: RenderProp;
  renderOpposite?: RenderProp;
  renderContent?: RenderProp;
  className?: string;
  /** Declarative `<BsTimelineItem>` children (used when no render-props). */
  children?: React.ReactNode;
}

const idOf = (item: TimelineItem, index: number): string | number => item.id ?? index;

/**
 * `<BsTimeline>` — React wrapper around `<mp-timeline>`.
 *
 * Render-props lower into `<mp-timeline-item>` children with their output in
 * the item's named slots (one shadow boundary). With no render-props, the
 * `items` array is set as the WC property, or declarative `<BsTimelineItem>`
 * children pass straight through.
 */
export function BsTimeline(props: BsTimelineProps): React.ReactElement {
  const {
    items,
    orientation = 'vertical',
    align = 'start',
    reverse = false,
    selectable = 'none',
    selection,
    onSelectionChange,
    onItemClick,
    renderMarker,
    renderTitle,
    renderTimestamp,
    renderOpposite,
    renderContent,
    className,
    children,
  } = props;

  const ref = React.useRef<MpTimeline | null>(null);
  const hasTemplates = !!(renderMarker || renderTitle || renderTimestamp || renderOpposite || renderContent);
  const lowering = hasTemplates && !!items;

  // Custom-event listeners (React doesn't bind custom events via on* props).
  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const onClick = (e: Event) => onItemClick?.((e as CustomEvent<TimelineItemClickDetail>).detail);
    const onSel = (e: Event) => {
      const detail = (e as CustomEvent<TimelineSelectionChangeDetail>).detail;
      if (items && items.length) {
        const ids = el.selectedIds ?? detail.selected.map((m, i) => m.id ?? i);
        const byId = new Map(items.map((it, i) => [idOf(it, i), it] as const));
        onSelectionChange?.(
          ids.map((id) => byId.get(id)).filter((x): x is TimelineItem => x !== undefined),
        );
      } else {
        onSelectionChange?.(detail.selected);
      }
    };
    el.addEventListener('item-click', onClick);
    el.addEventListener('selection-change', onSel);
    return () => {
      el.removeEventListener('item-click', onClick);
      el.removeEventListener('selection-change', onSel);
    };
  }, [items, onItemClick, onSelectionChange]);

  // Controlled selection → WC.
  React.useEffect(() => {
    const el = ref.current;
    if (!el || selectable === 'none') return;
    el.selectedIds = (selection ?? []).map((it, i) => idOf(it, i));
  }, [selection, selectable]);

  // Data path: set the WC `items` property only when not lowering to children.
  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    el.items = !lowering && items ? items : [];
  }, [items, lowering]);

  const sides = resolveSides(items?.length ?? 0, align, reverse);

  return (
    <mp-timeline
      ref={ref}
      orientation={orientation}
      align={align}
      reverse={reverse ? '' : undefined}
      selectable={selectable}
      className={className}
    >
      {lowering && items
        ? items.map((item, i) => {
            const len = items.length;
            const visualIndex = reverse ? len - 1 - i : i;
            const ctx: TimelineItemContext = {
              index: i,
              visualIndex,
              isFirst: visualIndex === 0,
              isLast: visualIndex === len - 1,
              orientation,
              side: sides[i] ?? 'start',
            };
            const time = item.time instanceof Date ? item.time.toLocaleDateString() : item.time;
            return (
              <mp-timeline-item
                key={item.id ?? i}
                item-id={item.id}
                title={item.title}
                description={item.description}
                time={time}
                icon={item.icon}
                color={item.color}
                item-class={item.cssClass}
                disabled={item.disabled ? '' : undefined}
              >
                {renderMarker && <span slot="marker">{renderMarker(item, ctx)}</span>}
                {renderTitle && <span slot="title">{renderTitle(item, ctx)}</span>}
                {renderTimestamp && <span slot="opposite">{renderTimestamp(item, ctx)}</span>}
                {renderOpposite && <span slot="opposite">{renderOpposite(item, ctx)}</span>}
                {renderContent && <div slot="content">{renderContent(item, ctx)}</div>}
              </mp-timeline-item>
            );
          })
        : children}
    </mp-timeline>
  );
}
