// libs/mintplayer-react-bootstrap/dropdown-menu/src/BsDropdownItem.tsx
import * as React from 'react';
import type { DropdownItemElement } from '@mintplayer/web-components/dropdown-menu';

export interface BsDropdownItemProps extends Omit<React.LiHTMLAttributes<HTMLLIElement>, 'value'> {
  /** Bootstrap `.active` appearance (also drives `aria-selected` in a listbox menu). */
  active?: boolean;
  /** Non-interactive; removed from the menu's roving order. */
  disabled?: boolean;
  /** Opaque value carried in the menu's `select` event detail. */
  value?: unknown;
}

/**
 * `<BsDropdownItem>` — a Bootstrap `.dropdown-item` for use inside
 * `<BsDropdownMenu>`. There is no per-item web component: it renders a plain
 * light-DOM `<li class="dropdown-item">` that the menu WC styles via its shadow
 * `::slotted(.dropdown-item)` rule. Put the navigable content inside, e.g.
 * `<BsDropdownItem><a href="/x">Action</a></BsDropdownItem>` (the companion
 * stylesheet resets the nested link). The opaque `value` is assigned as the
 * `dropdownValue` property on the `<li>` so the menu can carry it in its `select`
 * event — not as `value`, which `HTMLLIElement` owns as a native long (an object
 * or a string written there becomes 0).
 */
export const BsDropdownItem = React.forwardRef<HTMLLIElement, BsDropdownItemProps>(
  function BsDropdownItem({ active, disabled, value, className, children, ...rest }, ref) {
    const innerRef = React.useRef<HTMLLIElement & DropdownItemElement>(null);
    React.useImperativeHandle(ref, () => innerRef.current as HTMLLIElement);
    React.useEffect(() => {
      if (innerRef.current) innerRef.current.dropdownValue = value;
    }, [value]);

    const classes = ['dropdown-item', active ? 'active' : '', disabled ? 'disabled' : '', className ?? '']
      .filter(Boolean)
      .join(' ');

    return (
      <li ref={innerRef} className={classes} aria-disabled={disabled ? true : undefined} {...rest}>
        {children}
      </li>
    );
  },
);

// libs/mintplayer-vue-bootstrap/dropdown-menu/src/BsDropdownItem.vue
<script setup lang="ts">
// No per-item web component: renders a plain <li class="dropdown-item"> that the
// menu WC styles via its shadow `::slotted(.dropdown-item)` rule. Put navigable
// content inside, e.g. <BsDropdownItem><a href="/x">Action</a></BsDropdownItem>.
import { onMounted, ref, watch } from 'vue';
import type { DropdownItemElement } from '@mintplayer/web-components/dropdown-menu';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    /** Bootstrap `.active` appearance (also drives `aria-selected` in a listbox). */
    active?: boolean;
    /** Non-interactive; removed from the menu's roving order. */
    disabled?: boolean;
    /** Opaque value surfaced in the menu's `select` event — assigned as a JS property. */
    value?: unknown;
  }>(),
  { active: false, disabled: false },
);

const el = ref<(HTMLLIElement & DropdownItemElement) | null>(null);

// `value` is opaque, so push it to the <li> as its `dropdownValue` property (the
// menu reads it). Not `value`: HTMLLIElement owns that as a native long, which
// turns an object or a string into 0.
const syncValue = () => {
  if (el.value) el.value.dropdownValue = props.value;
};
onMounted(syncValue);
watch(() => props.value, syncValue);
</script>

<template>
  <li
    ref="el"
    v-bind="$attrs"
    class="dropdown-item"
    :class="{ active, disabled }"
    :aria-disabled="disabled ? 'true' : undefined"
  >
    <slot />
  </li>
</template>
