// libs/mintplayer-react-bootstrap/dropdown-menu/src/BsDropdownMenu.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import {
  MpDropdownMenu,
  type DropdownMode,
  type DropdownSelectEventDetail,
} from '@mintplayer/web-components/dropdown-menu';
// Companion light-DOM sheet (nested-link reset ::slotted can't reach). Imported
// here so it lands in the app's static CSS bundle — present with JS disabled.
import './dropdown-menu.css';

export interface BsDropdownMenuProps {
  /** `menu` (default, roving-tabindex keyboard nav) | `listbox`. */
  mode?: DropdownMode;
  /** px cap on the menu height; scrolls beyond. Maps to the `max-height` attribute. */
  maxHeight?: number;
  /** id of an external label, set as `aria-labelledby` on the list. Maps to `label-id`. */
  labelId?: string;
  /** Fires when an enabled item is activated; `detail.value` carries the item's value. */
  onSelect?: (event: CustomEvent<DropdownSelectEventDetail>) => void;
  className?: string;
  children?: React.ReactNode;
}

/**
 * Inner `@lit/react` component. `mode`/`maxHeight`/`labelId` are surfaced to the
 * WC as attributes (`mode`, `max-height`, `label-id`) — the layout/roles read the
 * attributes to keep the menu SSR- and no-JS-friendly — so `createComponent`
 * forwards them as React props → attributes. We retype its props to the clean
 * public surface; the runtime forwards everything to the element unchanged.
 */
type MpDropdownMenuInnerProps = Omit<BsDropdownMenuProps, 'maxHeight' | 'labelId'> & {
  'max-height'?: number;
  'label-id'?: string;
} & React.RefAttributes<MpDropdownMenu>;

const MpDropdownMenuComponent = createComponent({
  react: React,
  tagName: 'mp-dropdown-menu',
  elementClass: MpDropdownMenu,
  events: {
    onSelect: 'select' as EventName<CustomEvent<DropdownSelectEventDetail>>,
  },
}) as unknown as React.ForwardRefExoticComponent<MpDropdownMenuInnerProps>;

/**
 * React wrapper for `<mp-dropdown-menu>` — a Bootstrap `.dropdown-menu`.
 * Side-effect-registers the WC on import.
 *
 * The menu chrome is server-rendered as Declarative Shadow DOM (see
 * `injectMpDropdownDsd` in `@mintplayer/web-components/dropdown-menu/ssr`), so it
 * renders styled with JavaScript disabled. Slot `<BsDropdownItem>` /
 * `<BsDropdownDivider>` / `<BsDropdownHeader>` children. In `menu` mode (default)
 * the menu provides roving-tabindex keyboard navigation over the enabled items.
 *
 *     <BsDropdownMenu onSelect={(e) => console.log(e.detail.value)}>
 *       <BsDropdownHeader>Section</BsDropdownHeader>
 *       <BsDropdownItem value="a">First</BsDropdownItem>
 *       <BsDropdownDivider />
 *       <BsDropdownItem value="b" selected>Second</BsDropdownItem>
 *     </BsDropdownMenu>
 */
export const BsDropdownMenu = React.forwardRef<MpDropdownMenu, BsDropdownMenuProps>(function BsDropdownMenu(
  { maxHeight, labelId, ...props },
  ref,
) {
  return (
    <MpDropdownMenuComponent
      ref={ref}
      {...(maxHeight != null ? { 'max-height': maxHeight } : {})}
      {...(labelId != null ? { 'label-id': labelId } : {})}
      {...props}
    />
  );
});

// libs/mintplayer-vue-bootstrap/dropdown-menu/src/BsDropdownMenu.vue
<script setup lang="ts">
// Registers <mp-dropdown-menu> (and its sibling elements) on the client. On the
// SSR server this import runs after the lit-ssr DOM shim is installed (see the
// demo's entry-server.ts), so `customElements.define` doesn't throw in Node —
// same pattern as every other @mintplayer/vue-bootstrap wrapper.
import '@mintplayer/web-components/dropdown-menu';
import type {
  MpDropdownMenu,
  DropdownMode,
  DropdownSelectEventDetail,
} from '@mintplayer/web-components/dropdown-menu';
import { onBeforeUnmount, onMounted, ref } from 'vue';
// Companion light-DOM sheet (nested-link reset ::slotted can't reach). Imported
// here so it lands in the app's static CSS bundle — present with JS disabled.
import './dropdown-menu.css';

defineOptions({ inheritAttrs: false });

withDefaults(
  defineProps<{
    /** `menu` (default) exposes roving-tabindex menu semantics | `listbox`. */
    mode?: DropdownMode;
    /** Max panel height in px before the item list scrolls. */
    maxHeight?: number;
    /** `id` of an external element that labels the menu (aria-labelledby). */
    labelId?: string;
  }>(),
  {
    mode: 'menu',
  },
);

const emit = defineEmits<{ select: [detail: DropdownSelectEventDetail] }>();

const el = ref<MpDropdownMenu | null>(null);

function onSelect(event: Event) {
  emit('select', (event as CustomEvent<DropdownSelectEventDetail>).detail);
}

// `select` is a CustomEvent the WC dispatches; wire it up client-side only.
onMounted(() => el.value?.addEventListener('select', onSelect));
onBeforeUnmount(() => el.value?.removeEventListener('select', onSelect));
</script>

<template>
  <mp-dropdown-menu
    ref="el"
    v-bind="$attrs"
    :mode="mode"
    :max-height="maxHeight"
    :label-id="labelId"
  >
    <slot />
  </mp-dropdown-menu>
</template>
