// libs/mintplayer-react-bootstrap/datatable/src/BsDatatable.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import {
  MpDatatable,
  type RowEventDetail,
  type SortChangeEventDetail,
  type SelectionChangeEventDetail,
  type TreeRowExpandDetail,
  type TreeExpandedIdsChangeDetail,
  type FilterChangeDetail,
} from '@mintplayer/web-components/datatable';

/**
 * React wrapper for `<mp-datatable>`. Side-effect-registers the WC via
 * the import above. The `events` map surfaces each CustomEvent the WC
 * dispatches as an idiomatic React `on*` prop with full detail typing.
 *
 * Note: complex props like `columns`, `data`, `expandedIds`, `idKey`,
 * and `childCountKey` are typed by the MpDatatable class fields. Set
 * them as JS objects via the React props; @lit/react forwards them as
 * properties (not attributes) so Sets/arrays/functions round-trip
 * correctly.
 *
 * Server paging: set the `fetch` prop to a callback returning
 * `{ data, totalRecords }`. `createComponent` forwards it to the element's
 * `fetch` property, and the web component owns the whole loop — initial page,
 * on-demand windows, tree children, pagination, sort/perPage reloads. The
 * consumer wires nothing else (no `totalRecords`, no event bridge). To
 * re-query with an unchanged callback, call `reload({ resetPage? })` on the
 * element ref; `applyFetchState({ fetch, sortColumns, page, perPage })` applies
 * several of those as one change (one request). Pass a stable `fetch`
 * (`useCallback`): a new function is a new source and reloads.
 *
 * Selection: `selectionMode` is `'none' | 'single' | 'multiple' | 'checkbox'`
 * (`'checkbox'` selects only through the checkbox column; a row click just
 * opens the row). Act on `onSelectionChange`'s `detail.selectedIds` — it is
 * authoritative and holds every selected key, across pages. `detail.selectedRows`
 * is index-aligned with it and covers every key whose row the element has ever
 * seen, off-page rows included; it is `undefined` where a key's row was never
 * seen, so narrow before use. The `selectedRows` prop REPLACES the selection
 * with the given rows (keys derived through `rowKey`, rows remembered even
 * when not loaded) and emits no event; it is pushed when its reference changes,
 * never on an unrelated re-render. `rowLabel: (row) => string` names each
 * row's checkbox ("Select {label}"); it defaults to the first cell's text.
 *
 * Filtering: mark a column `filterable` and it gets the built-in panel — search,
 * include/exclude, checkbox list, clear — with no wrapper code, because the
 * panel lives in the web component. `distincts` supplies the value lists when
 * the element does not hold every row; `onFilterChange` reports the selection,
 * which the consumer applies. A column's `filterRenderer` replaces the panel
 * entirely, and must return a STABLE node: it is mounted once per open, and
 * repainting it is the renderer's job via `context.onChange`.
 */
const BsDatatableElement = createComponent({
  react: React,
  tagName: 'mp-datatable',
  elementClass: MpDatatable,
  events: {
    onPageChange: 'mp-datatable-page-change' as EventName<CustomEvent<{ page: number }>>,
    onPerPageChange: 'mp-datatable-per-page-change' as EventName<CustomEvent<{ perPage: number }>>,
    onSortChange: 'mp-datatable-sort-change' as EventName<CustomEvent<SortChangeEventDetail>>,
    onRowClick: 'mp-datatable-row-click' as EventName<CustomEvent<RowEventDetail>>,
    onRowDblClick: 'mp-datatable-row-dblclick' as EventName<CustomEvent<RowEventDetail>>,
    onRowContextMenu: 'mp-datatable-row-contextmenu' as EventName<CustomEvent<RowEventDetail>>,
    onSelectionChange: 'mp-datatable-selection-change' as EventName<CustomEvent<SelectionChangeEventDetail>>,
    onRowExpand: 'mp-datatable-row-expand' as EventName<CustomEvent<TreeRowExpandDetail>>,
    onRowCollapse: 'mp-datatable-row-collapse' as EventName<CustomEvent<TreeRowExpandDetail>>,
    onExpandedIdsChange: 'mp-datatable-expanded-ids-change' as EventName<CustomEvent<TreeExpandedIdsChangeDetail>>,
    onFilterOpen: 'mp-datatable-filter-open' as EventName<CustomEvent<{ column: string }>>,
    onFilterClose: 'mp-datatable-filter-close' as EventName<CustomEvent<{ column: string }>>,
    onFilterChange: 'mp-datatable-filter-change' as EventName<CustomEvent<FilterChangeDetail>>,
  },
});

export type BsDatatableProps = Omit<React.ComponentProps<typeof BsDatatableElement>, 'ref'>;

/**
 * `createComponent` re-assigns every element property on every render (it
 * leaves dirty-checking to the element). That is harmless for every prop but
 * `selectedRows`, whose setter REPLACES the selection: an unrelated re-render
 * would revert the user's clicks to the stale prop. So `selectedRows` is held
 * back and pushed only when its own reference changes (as the Vue wrapper does).
 * The effect runs after the inner element's, so `rowKey` and `data` are set
 * before the keys are derived.
 */
export const BsDatatable = React.forwardRef<MpDatatable, BsDatatableProps>(
  function BsDatatable({ selectedRows, ...rest }, ref) {
    const innerRef = React.useRef<MpDatatable>(null);
    React.useImperativeHandle(ref, () => innerRef.current as MpDatatable);
    React.useLayoutEffect(() => {
      if (innerRef.current && selectedRows !== undefined) innerRef.current.selectedRows = selectedRows;
    }, [selectedRows]);
    return <BsDatatableElement ref={innerRef} {...rest} />;
  },
);

// libs/mintplayer-vue-bootstrap/datatable/src/BsDatatable.vue
<script setup lang="ts">
// Side-effect-registers <mp-datatable> via the upstream WC entry.
import '@mintplayer/web-components/datatable';
import {
  MpDatatable,
  type DatatableColumnDef,
  type DatatableFetch,
  type DatatableFetchState,
  type DatatableReloadOptions,
  type RowKey,
  type RowRenderer,
  type DatatableSelectionMode,
  type TreeIdKey,
  type TreeSelectionStrategy,
  type TreeRowExpandDetail,
  type TreeExpandedIdsChangeDetail,
  type RowEventDetail,
  type SortChangeEventDetail,
  type SelectionChangeEventDetail,
  type DatatableDistincts,
  type DatatableLabels,
  type FilterChangeDetail,
} from '@mintplayer/web-components/datatable';
import { ref, watch, onMounted, onBeforeUnmount } from 'vue';

defineOptions({ inheritAttrs: false });

// Object-valued props (arrays, Sets, functions) must be assigned to the
// element's JS properties — Vue's attribute serialization can't carry them.
// Scalar props (`tree`, `virtualScroll`, `itemSize`, `selectionMode`, …)
// flow through `v-bind="$attrs"` on the template element.
const props = defineProps<{
  columns?: DatatableColumnDef[];
  data?: unknown[];
  /** Server-paged source. The WC owns the whole fetch loop; nothing else to wire. */
  fetch?: DatatableFetch | null;
  rowKey?: RowKey;
  /**
   * Whole-row renderer. Returns the cell nodes for a row, which the WC mounts
   * in its (light-DOM) table — so the page's stylesheets and the consumer's own
   * component CSS style them normally. Exposed for parity with Angular/React.
   */
  rowRenderer?: RowRenderer;
  // Tree-mode JS-property props
  tree?: boolean;
  idKey?: TreeIdKey | string | null;
  childCountKey?: string | null;
  treeIndent?: number;
  expandedIds?: Set<unknown> | ReadonlyArray<unknown>;
  /** `'none' | 'single' | 'multiple' | 'checkbox'` (`'checkbox'`: selection only through the checkbox column). */
  selectionMode?: DatatableSelectionMode;
  selectionStrategy?: TreeSelectionStrategy;
  /** The selected keys; `v-model:selectedIds`. Authoritative. */
  selectedIds?: string[] | ReadonlyArray<string>;
  /**
   * Seeds the selection with row objects: REPLACES it, deriving the keys
   * through `rowKey` and remembering the rows, so rows that are not loaded
   * (another page, not fetched yet) are still reported in
   * `selectionChange`'s `detail.selectedRows`. One-way: it is pushed when it
   * changes, and takes precedence over `selectedIds` when both change at once.
   * Read the selection back from `selectionChange` / `v-model:selectedIds`.
   */
  selectedRows?: unknown[] | ReadonlyArray<unknown>;
  /**
   * Names a row for its selection checkbox ("Select {label}"). Defaults to the
   * text of the row's first cell, then the row number.
   */
  rowLabel?: ((row: unknown) => string) | null;
  /**
   * Source of distinct values for the filter panels. Required whenever the
   * element does not hold every row -- with `fetch`, external paging, or a tree
   * with lazily loaded children, a locally computed list would omit values, so
   * none is computed.
   */
  distincts?: DatatableDistincts | null;
  /** Partial override of the component's user-visible strings. */
  labels?: Partial<DatatableLabels> | null;
}>();

const emit = defineEmits<{
  (e: 'update:expandedIds', value: Set<unknown>): void;
  (e: 'update:selectedIds', value: string[]): void;
  (e: 'rowExpand', detail: TreeRowExpandDetail): void;
  (e: 'rowCollapse', detail: TreeRowExpandDetail): void;
  (e: 'sortChange', detail: SortChangeEventDetail): void;
  // `detail.selectedIds` is authoritative; `detail.selectedRows` is
  // index-aligned with it, `undefined` where a key's row was never seen.
  (e: 'selectionChange', detail: SelectionChangeEventDetail): void;
  (e: 'rowClick', detail: RowEventDetail): void;
  (e: 'rowDblClick', detail: RowEventDetail): void;
  (e: 'rowContextMenu', detail: RowEventDetail): void;
  (e: 'pageChange', detail: { page: number }): void;
  (e: 'perPageChange', detail: { perPage: number }): void;
  (e: 'filterChange', detail: FilterChangeDetail): void;
}>();

const el = ref<MpDatatable | null>(null);

const syncProps = () => {
  if (!el.value) return;
  el.value.columns = (props.columns ?? []) as DatatableColumnDef[];
  // `fetch` and static `data` are mutually exclusive — when fetching, the WC
  // owns the rows, so don't also push `data` (it would clobber fetched pages).
  // When `fetch` is cleared at runtime, drop the stale callback off the WC and
  // fall back to static `data` (otherwise the WC keeps server-paging forever).
  if (props.fetch != null) {
    el.value.fetch = props.fetch;
  } else {
    el.value.fetch = null;
    el.value.data = props.data ?? [];
  }
  if (props.rowKey !== undefined) el.value.rowKey = props.rowKey;
  if (props.rowRenderer !== undefined) el.value.rowRenderer = props.rowRenderer;
  if (props.tree !== undefined) el.value.tree = props.tree;
  if (props.idKey !== undefined) el.value.idKey = props.idKey as TreeIdKey | null;
  if (props.childCountKey !== undefined) el.value.childCountKey = props.childCountKey;
  if (props.treeIndent !== undefined) el.value.treeIndent = props.treeIndent;
  if (props.selectionMode !== undefined) el.value.selectionMode = props.selectionMode;
  if (props.selectionStrategy !== undefined) el.value.selectionStrategy = props.selectionStrategy;
  if (props.distincts !== undefined) el.value.distincts = props.distincts;
  if (props.labels !== undefined) el.value.labels = props.labels ?? undefined;
  if (props.rowLabel !== undefined) el.value.rowLabel = props.rowLabel;
};

// Not part of `syncProps`: these three are STATE the user changes in the
// element (clicks, expansion), and their setters replace that state. Bound
// one-way (no `v-model`), the prop keeps its first value, so re-pushing it on
// every unrelated prop change would revert the user's clicks — and a stale
// `selectedIds` would override a `selectedRows` seed. Each is pushed on mount
// and when its OWN value changes only.
const syncExpandedIds = () => {
  if (!el.value || props.expandedIds === undefined) return;
  el.value.expandedIds = new Set(props.expandedIds);
};
const syncSelectedIds = () => {
  if (!el.value || props.selectedIds === undefined) return;
  el.value.selectedIds = [...props.selectedIds];
};
const syncSelectedRows = () => {
  if (!el.value || props.selectedRows === undefined) return;
  el.value.selectedRows = [...props.selectedRows];
};

// One handler per dispatched WC event; the WC's `mp-datatable-*` names
// flatten to camelCase Vue events. `update:expandedIds` is the v-model
// channel so `v-model:expandedIds` works on consumers.
const handlers: Record<string, (e: Event) => void> = {
  'mp-datatable-row-expand': (e) => emit('rowExpand', (e as CustomEvent<TreeRowExpandDetail>).detail),
  'mp-datatable-row-collapse': (e) => emit('rowCollapse', (e as CustomEvent<TreeRowExpandDetail>).detail),
  'mp-datatable-expanded-ids-change': (e) => {
    const detail = (e as CustomEvent<TreeExpandedIdsChangeDetail>).detail;
    emit('update:expandedIds', new Set(detail.expandedIds));
  },
  'mp-datatable-sort-change': (e) => emit('sortChange', (e as CustomEvent<SortChangeEventDetail>).detail),
  'mp-datatable-selection-change': (e) => {
    const detail = (e as CustomEvent<SelectionChangeEventDetail>).detail;
    emit('selectionChange', detail);
    emit('update:selectedIds', [...detail.selectedIds]);
  },
  'mp-datatable-row-click': (e) => emit('rowClick', (e as CustomEvent<RowEventDetail>).detail),
  'mp-datatable-row-dblclick': (e) => emit('rowDblClick', (e as CustomEvent<RowEventDetail>).detail),
  'mp-datatable-row-contextmenu': (e) => emit('rowContextMenu', (e as CustomEvent<RowEventDetail>).detail),
  'mp-datatable-page-change': (e) => emit('pageChange', (e as CustomEvent<{ page: number }>).detail),
  'mp-datatable-per-page-change': (e) => emit('perPageChange', (e as CustomEvent<{ perPage: number }>).detail),
  'mp-datatable-filter-change': (e) => emit('filterChange', (e as CustomEvent<FilterChangeDetail>).detail),
};

const attachEvents = () => {
  if (!el.value) return;
  for (const [name, handler] of Object.entries(handlers)) {
    el.value.addEventListener(name, handler);
  }
};

const detachEvents = () => {
  if (!el.value) return;
  for (const [name, handler] of Object.entries(handlers)) {
    el.value.removeEventListener(name, handler);
  }
};

onMounted(() => {
  syncProps();
  syncExpandedIds();
  // Keys first, rows last: a `selectedRows` seed wins over `selectedIds`.
  syncSelectedIds();
  syncSelectedRows();
  attachEvents();
});

onBeforeUnmount(detachEvents);

watch(() => props.columns, syncProps, { deep: false });
watch(() => props.data, syncProps, { deep: false });
watch(() => props.fetch, syncProps);
watch(() => props.rowKey, syncProps);
watch(() => props.tree, syncProps);
watch(() => props.idKey, syncProps);
watch(() => props.childCountKey, syncProps);
watch(() => props.treeIndent, syncProps);
watch(() => props.selectionMode, syncProps);
watch(() => props.selectionStrategy, syncProps);
watch(() => props.distincts, syncProps);
watch(() => props.labels, syncProps, { deep: false });
watch(() => props.rowLabel, syncProps);
watch(() => props.expandedIds, syncExpandedIds, { deep: false });
// Watchers of one flush run in definition order: when both change at once,
// the rows are pushed last and win, as documented on `selectedRows`.
watch(() => props.selectedIds, syncSelectedIds, { deep: false });
watch(() => props.selectedRows, syncSelectedRows, { deep: false });

/**
 * Re-queries `fetch` for the current sort, page and page size (the server data
 * changed). The selection is kept; `resetPage: true` also returns to page 1.
 */
const reload = (options?: DatatableReloadOptions) => el.value?.reload(options);

/**
 * Applies any of `fetch`, `sortColumns`, `page` and `perPage` as one change,
 * costing at most one request. See `MpDatatable.applyFetchState`.
 */
const applyFetchState = (state: DatatableFetchState) => el.value?.applyFetchState(state);

// The WC owns the fetch loop; these are the only imperative entry points,
// plus the underlying element for advanced access.
defineExpose({ el, reload, applyFetchState });
</script>

<template>
  <mp-datatable ref="el" v-bind="$attrs" />
</template>
