// libs/mintplayer-vue-bootstrap/dock/src/BsDockManager.vue
<script setup lang="ts">
import '@mintplayer/web-components/dock';
import {
  MintDockManagerElement,
  type DockLayoutSnapshot,
} from '@mintplayer/web-components/dock';
import { onMounted, ref, watch } from 'vue';

defineOptions({ inheritAttrs: false });

// `layout` is an object — Vue can't bind objects as DOM attributes, so we
// forward it via the WC's property setter after mount. v-model surface is
// the `layout` JS prop + the `dock-layout-changed` CustomEvent.
const modelValue = defineModel<DockLayoutSnapshot | null>('layout');

const el = ref<MintDockManagerElement | null>(null);

const syncToEl = (v: DockLayoutSnapshot | null | undefined) => {
  if (el.value) el.value.layout = v ?? null;
};

onMounted(() => syncToEl(modelValue.value));
watch(modelValue, syncToEl);

function onLayoutChanged(e: Event) {
  const detail = (e as CustomEvent<DockLayoutSnapshot>).detail;
  if (detail) modelValue.value = detail;
}
</script>

<template>
  <mint-dock-manager
    ref="el"
    v-bind="$attrs"
    @dock-layout-changed="onLayoutChanged"
  >
    <slot />
  </mint-dock-manager>
</template>

// libs/mintplayer-react-bootstrap/dock/src/BsDockManager.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import {
  MintDockManagerElement,
  type DockLayoutSnapshot,
} from '@mintplayer/web-components/dock';

/**
 * React wrapper for `<mint-dock-manager>`. Side-effect-registers the WC
 * via the import above. The `layout` JS prop is an object, so @lit/react
 * forwards it as a property — pass a snapshot directly, no JSON
 * stringification needed.
 *
 * Project pane content via native named slots:
 *   <BsDockManager layout={layout}>
 *     <div slot="panel-1">…</div>
 *     <div slot="panel-2">…</div>
 *   </BsDockManager>
 */
export const BsDockManager = createComponent({
  react: React,
  tagName: 'mint-dock-manager',
  elementClass: MintDockManagerElement,
  events: {
    onLayoutChanged: 'dock-layout-changed' as EventName<CustomEvent<DockLayoutSnapshot>>,
  },
});
