// libs/mintplayer-react-bootstrap/navbar/src/BsNavbar.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import {
  MpNavbar,
  type NavbarBreakpoint,
  type NavbarExpandedChangeEventDetail,
} from '@mintplayer/web-components/navbar';

export interface BsNavbarProps {
  /** Bootstrap breakpoint name (`xs`…`xxl`, default `md`); at/above it the nav is inline. */
  breakpoint?: NavbarBreakpoint;
  /** Background: a theme color (`primary`…`dark`) or adaptive `body` / `body-secondary` / `body-tertiary`. */
  color?: string;
  /** Programmatic collapse state (narrow mode); reflects the toggle. */
  expanded?: boolean;
  /** `fixed` pins the bar to the top of the viewport, full width; omit for in-flow. */
  positioning?: 'fixed';
  /** Landmark label for the `<nav>` (default `Main navigation`). Maps to `aria-label`. */
  ariaLabel?: string;
  /** Fires when the collapse toggles; `detail.expanded` carries the new state. */
  onExpandedChange?: (event: CustomEvent<NavbarExpandedChangeEventDetail>) => void;
  className?: string;
  children?: React.ReactNode;
}

/**
 * Inner `@lit/react` component. `breakpoint`/`color` aren't reactive element
 * *properties* (the WC reads them as attributes to keep the collapse pure-CSS /
 * SSR- and no-JS-friendly), so `createComponent` forwards them as React props →
 * attributes. `ariaLabel` is surfaced as the `aria-label` attribute, and
 * `expanded` as the reflected boolean attribute. We retype its props to the
 * clean public surface; the runtime forwards everything to the element unchanged.
 */
type MpNavbarInnerProps = Omit<BsNavbarProps, 'ariaLabel' | 'expanded'> & {
  'aria-label'?: string;
  expanded?: '';
} & React.RefAttributes<MpNavbar>;

const MpNavbarComponent = createComponent({
  react: React,
  tagName: 'mp-navbar',
  elementClass: MpNavbar,
  events: {
    onExpandedChange: 'expandedchange' as EventName<CustomEvent<NavbarExpandedChangeEventDetail>>,
  },
}) as unknown as React.ForwardRefExoticComponent<MpNavbarInnerProps>;

/**
 * React wrapper for `<mp-navbar>` — the responsive Bootstrap navbar.
 * Side-effect-registers the WC on import.
 *
 * The bar chrome (hamburger toggle, collapsible region) is server-rendered as
 * Declarative Shadow DOM (see `injectMpNavbarDsd` in
 * `@mintplayer/web-components/navbar/ssr`), so it collapses/reveals via its
 * pure-CSS state machine with JavaScript disabled. Place the brand in
 * `<BsNavbarBrand slot="brand">`, left items as default `<BsNavbarItem>`
 * children, and right-aligned items with `slot="end"`.
 *
 *     <BsNavbar breakpoint="lg" color="body-tertiary">
 *       <BsNavbarBrand slot="brand"><a href="/">MyApp</a></BsNavbarBrand>
 *       <BsNavbarItem active><a href="/home">Home</a></BsNavbarItem>
 *     </BsNavbar>
 */
export const BsNavbar = React.forwardRef<MpNavbar, BsNavbarProps>(function BsNavbar(
  { ariaLabel, expanded, ...props },
  ref,
) {
  return (
    <MpNavbarComponent
      ref={ref}
      {...(ariaLabel != null ? { 'aria-label': ariaLabel } : {})}
      {...(expanded ? { expanded: '' as const } : {})}
      {...props}
    />
  );
});

// libs/mintplayer-vue-bootstrap/navbar/src/BsNavbar.vue
<script setup lang="ts">
// Registers <mp-navbar> (and its sibling elements) on the client. On the SSR
// server this import runs after the lit-ssr DOM shim is installed (see the
// demo's entry-server.ts), so `customElements.define` doesn't throw in Node —
// same pattern as every other @mintplayer/vue-bootstrap wrapper.
import '@mintplayer/web-components/navbar';
import type {
  MpNavbar,
  NavbarBreakpoint,
  NavbarExpandedChangeEventDetail,
} from '@mintplayer/web-components/navbar';
import { onBeforeUnmount, onMounted, ref } from 'vue';

defineOptions({ inheritAttrs: false });

withDefaults(
  defineProps<{
    /** Breakpoint at/above which the navbar lays out horizontally. Default `md`. */
    breakpoint?: NavbarBreakpoint;
    /** Bootstrap color (`primary`/`dark`/…) or adaptive (`body`/`body-secondary`/`body-tertiary`). */
    color?: string;
    /** Reflected open state of the collapsed menu (boolean attribute). */
    expanded?: boolean;
    /** Accessible label for the navbar landmark. */
    ariaLabel?: string;
    /** `fixed` pins the bar to the top of the viewport, full width; omit for in-flow. */
    positioning?: 'fixed';
  }>(),
  {
    breakpoint: 'md',
  },
);

const emit = defineEmits<{ expandedchange: [detail: NavbarExpandedChangeEventDetail] }>();

const el = ref<MpNavbar | null>(null);

function onExpandedchange(event: Event) {
  emit('expandedchange', (event as CustomEvent<NavbarExpandedChangeEventDetail>).detail);
}

// `expandedchange` is a CustomEvent the WC dispatches; wire it up client-side only.
onMounted(() => el.value?.addEventListener('expandedchange', onExpandedchange));
onBeforeUnmount(() => el.value?.removeEventListener('expandedchange', onExpandedchange));
</script>

<template>
  <!--
    Brand + items are server-rendered as Declarative Shadow DOM (see
    injectMpNavbarDsd in @mintplayer/web-components/navbar/ssr), so the bar
    renders with JavaScript disabled. Place the brand with slot="brand",
    right-aligned items with slot="end", everything else is left items:

      <BsNavbar breakpoint="lg" color="body-tertiary">
        <BsNavbarBrand>…</BsNavbarBrand>
        <BsNavbarItem active><a href="…">Home</a></BsNavbarItem>
        <BsNavbarItem slot="end"><a href="…">Sign in</a></BsNavbarItem>
      </BsNavbar>
  -->
  <mp-navbar
    ref="el"
    v-bind="$attrs"
    :breakpoint="breakpoint"
    :color="color"
    :aria-label="ariaLabel"
    :expanded="expanded ? '' : undefined"
    :positioning="positioning"
  >
    <slot />
  </mp-navbar>
</template>
