// libs/mintplayer-vue-bootstrap/carousel/src/BsCarousel.vue
<script setup lang="ts">
// Registers <mp-carousel> on the client. On the SSR server this import runs
// after the lit-ssr DOM shim is installed (see the demo's entry-server.ts), so
// customElements.define doesn't throw in Node — same pattern as every other
// @mintplayer/vue-bootstrap wrapper.
import '@mintplayer/web-components/carousel';
import type {
  CarouselAnimation,
  CarouselOrientation,
  CarouselPausedChangeEventDetail,
  CarouselSlideChangeEventDetail,
  MpCarousel,
} from '@mintplayer/web-components/carousel';
import { onBeforeUnmount, onMounted, ref } from 'vue';

defineOptions({ inheritAttrs: false });

withDefaults(
  defineProps<{
    animation?: CarouselAnimation;
    orientation?: CarouselOrientation;
    /** Show the indicator dots. */
    indicators?: boolean;
    /** Auto-advance interval in ms; omit for no autoplay. */
    interval?: number;
    /** Wrap around at the ends. */
    wrap?: boolean;
    /** Arrow/Home/End navigation on the focused viewport. */
    keyboardEvents?: boolean;
    /** Accessible label for the carousel region. */
    ariaLabel?: string;
  }>(),
  { animation: 'slide', orientation: 'horizontal', wrap: true, keyboardEvents: true },
);

/** Two-way: whether autoplay is paused (v-model:paused). */
const paused = defineModel<boolean>('paused', { default: false });

const emit = defineEmits<{
  slideChange: [detail: CarouselSlideChangeEventDetail];
  animationStart: [];
  animationEnd: [];
}>();

const el = ref<MpCarousel | null>(null);

function onSlideChange(event: Event) {
  emit('slideChange', (event as CustomEvent<CarouselSlideChangeEventDetail>).detail);
}
function onPausedChange(event: Event) {
  paused.value = (event as CustomEvent<CarouselPausedChangeEventDetail>).detail.paused;
}
function onAnimationStart() {
  emit('animationStart');
}
function onAnimationEnd() {
  emit('animationEnd');
}

// CustomEvents the WC dispatches; wired client-side only.
onMounted(() => {
  el.value?.addEventListener('slide-change', onSlideChange);
  el.value?.addEventListener('paused-change', onPausedChange);
  el.value?.addEventListener('animation-start', onAnimationStart);
  el.value?.addEventListener('animation-end', onAnimationEnd);
});
onBeforeUnmount(() => {
  el.value?.removeEventListener('slide-change', onSlideChange);
  el.value?.removeEventListener('paused-change', onPausedChange);
  el.value?.removeEventListener('animation-start', onAnimationStart);
  el.value?.removeEventListener('animation-end', onAnimationEnd);
});
</script>

<template>
  <mp-carousel
    ref="el"
    v-bind="$attrs"
    :animation="animation"
    :orientation="orientation"
    :indicators="indicators ? '' : undefined"
    :interval="interval && interval > 0 ? interval : undefined"
    :wrap="wrap === false ? 'false' : undefined"
    :keyboard-events="keyboardEvents === false ? 'false' : undefined"
    :paused="paused ? '' : undefined"
    :aria-label="ariaLabel"
  >
    <slot />
    <!-- Custom play/pause control: a native custom element needs the slot
         attribute on a REAL child (Vue template slot syntax can't provide it). -->
    <span v-if="$slots['play-pause']" slot="play-pause"><slot name="play-pause" /></span>
  </mp-carousel>
</template>

// libs/mintplayer-react-bootstrap/carousel/src/BsCarousel.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
// Side-effect-registers the WC on import. The React SSR entry installs the
// lit-ssr DOM shim before any wrapper module loads, so this is Node-safe.
import {
  MpCarousel,
  type CarouselAnimation,
  type CarouselOrientation,
  type CarouselPausedChangeEventDetail,
  type CarouselSlideChangeEventDetail,
} from '@mintplayer/web-components/carousel';

export interface BsCarouselProps {
  /** Slide transition: `slide` (default), `fade`, or `none`. */
  animation?: CarouselAnimation;
  orientation?: CarouselOrientation;
  /** Show the indicator dots. */
  indicators?: boolean;
  /** Auto-advance interval in ms; omit for no autoplay. */
  interval?: number;
  /** Wrap around at the ends (default true). */
  wrap?: boolean;
  /** Arrow/Home/End navigation on the focused viewport (default true). */
  keyboardEvents?: boolean;
  /** Whether autoplay is paused (controlled via onPausedChange). */
  paused?: boolean;
  /** Accessible label for the carousel region. Maps to `aria-label`. */
  ariaLabel?: string;
  onSlideChange?: (event: CustomEvent<CarouselSlideChangeEventDetail>) => void;
  onPausedChange?: (event: CustomEvent<CarouselPausedChangeEventDetail>) => void;
  onAnimationStart?: (event: CustomEvent<void>) => void;
  onAnimationEnd?: (event: CustomEvent<void>) => void;
  className?: string;
  /** Slides (plus an optional element with slot="play-pause"). */
  children?: React.ReactNode;
}

/**
 * Inner `@lit/react` component, retyped to the wire shape the facade emits:
 * attribute-named/attribute-valued props so React SSR serialises them into the
 * HTML (the DSD injector and the no-JS CSS select on the attributes), while on
 * the client `createComponent` routes prototype-matching names through the
 * WC's reflecting property setters — same single store either way.
 */
type MpCarouselInnerProps = {
  animation?: CarouselAnimation;
  orientation?: CarouselOrientation;
  indicators?: boolean;
  interval?: number;
  wrap?: 'false';
  'keyboard-events'?: 'false';
  paused?: boolean;
  'aria-label'?: string;
  className?: string;
  children?: React.ReactNode;
  onSlideChange?: (event: CustomEvent<CarouselSlideChangeEventDetail>) => void;
  onPausedChange?: (event: CustomEvent<CarouselPausedChangeEventDetail>) => void;
  onAnimationStart?: (event: CustomEvent<void>) => void;
  onAnimationEnd?: (event: CustomEvent<void>) => void;
} & React.RefAttributes<MpCarousel>;

const MpCarouselComponent = createComponent({
  react: React,
  tagName: 'mp-carousel',
  elementClass: MpCarousel,
  events: {
    onSlideChange: 'slide-change' as EventName<CustomEvent<CarouselSlideChangeEventDetail>>,
    onPausedChange: 'paused-change' as EventName<CustomEvent<CarouselPausedChangeEventDetail>>,
    onAnimationStart: 'animation-start' as EventName<CustomEvent<void>>,
    onAnimationEnd: 'animation-end' as EventName<CustomEvent<void>>,
  },
}) as unknown as React.ForwardRefExoticComponent<MpCarouselInnerProps>;

export const BsCarousel = React.forwardRef<MpCarousel, BsCarouselProps>(function BsCarousel(
  { ariaLabel, indicators, interval, wrap, keyboardEvents, paused, ...props },
  ref,
) {
  return (
    <MpCarouselComponent
      ref={ref}
      {...(ariaLabel != null ? { 'aria-label': ariaLabel } : {})}
      {...(indicators ? { indicators: true } : {})}
      {...(interval && interval > 0 ? { interval } : {})}
      {...(wrap === false ? { wrap: 'false' as const } : {})}
      {...(keyboardEvents === false ? { 'keyboard-events': 'false' as const } : {})}
      {...(paused ? { paused: true } : {})}
      {...props}
    />
  );
});
