// libs/mintplayer-react-bootstrap/pagination/src/BsPagination.tsx
import * as React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { MpPagination, type PageChangeEventDetail } from '@mintplayer/web-components/pagination';
/**
 * React wrapper for `<mp-pagination>`. Side-effect-registers the WC via
 * the import above. The pagination WC fires its own custom event name
 * (`mp-pagination-page-change`); the `events` map below surfaces it as
 * an `onMpPaginationPageChange` typed React prop.
 */
export const BsPagination = createComponent({
  react: React,
  tagName: 'mp-pagination',
  elementClass: MpPagination,
  events: {
    onMpPaginationPageChange: 'mp-pagination-page-change' as EventName<CustomEvent<PageChangeEventDetail>>,
  },
});

// libs/mintplayer-vue-bootstrap/pagination/src/BsPagination.vue
<script setup lang="ts">
// Side-effect-registers <mp-pagination> via the upstream WC entry.
import '@mintplayer/web-components/pagination';
import type { MpPagination, PageChangeEventDetail } from '@mintplayer/web-components/pagination';
import { ref, watch, onMounted } from 'vue';
defineOptions({ inheritAttrs: false });

// The pagination WC's v-model surface is the `selectedPageNumber` property
// (number) + the `mp-pagination-page-change` CustomEvent<{ page: number }>.
const modelValue = defineModel<number>();
const el = ref<MpPagination | null>(null);

const syncToEl = (v: number | undefined) => {
  if (el.value && typeof v === 'number') el.value.selectedPageNumber = v;
};

onMounted(() => syncToEl(modelValue.value));
watch(modelValue, syncToEl);

function onPageChange(e: Event) {
  const detail = (e as CustomEvent<PageChangeEventDetail>).detail;
  modelValue.value = detail.page;
}
</script>

<template>
  <mp-pagination
    ref="el"
    v-bind="$attrs"
    @mp-pagination-page-change="onPageChange"
  >
    <slot />
  </mp-pagination>
</template>
